# Generated by Django 5.0.3 on 2024-06-10 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attack_type', models.CharField(max_length=254)),
                ('file', models.FileField(upload_to='attack-files/%y/%m/%d/')),
                ('attack_timing', models.DateTimeField(auto_now_add=True)),
                ('attack_input', models.CharField(max_length=700)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'logs',
                'managed': True,
            },
        ),
    ]
